mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from my_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include('my_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),
]
 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
urlpatterns = [

    path('',views.profiles,name="profile"),
    path('loginPage/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('register/',views.registerUser,name='register'),
    path('profile/',views.profiles,name="profile"),
    path('userprofile/<str:pk>/',views.userProfile,name="userprofile"),
    path('account/',views.userAccounts,name="account"),
    path('edit-account/',views.editAccount,name="editAccount"),

]

my_app/models.py
from pyexpat import features
from unicodedata import name
from django.db import models
from django import forms
import uuid
from users.models import Profile
# Create your models here.
class Tag(models.Model):
 name = models.CharField(max_length=200)
 created_at = models.DateTimeField(auto_now_add=True)
 id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
 def __str__(self):
        return self.name
class doctor(models.Model):
    name = models.CharField(max_length=200,null=False, blank=False)
    specialty = models.CharField(max_length=200,null=False, blank=False)
    certification_CHOICES = (
        ('A', 'American Board'),
        ('B', 'Bachelor'),
    )
    tags = models.ManyToManyField(Tag,blank=True)
    certification = models.CharField(max_length=30, choices=certification_CHOICES)
    description = models.TextField(null=True, blank=True)
    vote_total = models.IntegerField(default=0,null=True, blank=True)
    vote_ratio = models.IntegerField(default=0,null=True, blank=True)
    # id = models.UUIDField(default=uuid.uuid4, unique=True,
    #                       primary_key=True, editable=False)
    
    def __str__(self):
     return str(self.name)
    
class Project(models.Model):
    user = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.CASCADE)
    doctor = models.ForeignKey(doctor,null=True,blank=True,on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True,default="default.jpg")
    demo_link = models.CharField(max_length=2000,null=True, blank=True)
    source_link = models.CharField(max_length=2000,null=True,blank=True)
    tags = models.ManyToManyField(Tag,blank=True)
    vote_total = models.IntegerField(default=0,null=True, blank=True)
    vote_ratio = models.IntegerField(default=0,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return self.title
class reviews(models.Model):
    VOTE_CHOICES = (
        ('up','Up Vote'),
        ('down','Down Vote'),
    )
    #owner =
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.TextField(max_length=200,choices=VOTE_CHOICES)
    
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    def __str__(self):
        return self.value

templates/index.html
<!DOCTYPE html>
<html lang="en">
 
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>Bondhu - A friend in need</title>
  </head>
    <body>
      {% include 'navbar.html' %}
      {% if messages %}

      {% for message in messages %}
      <div class="alert  alert--{{message.tags}}">
          <p class="alert__message">{{message}}</p>
          <button class="alert__close">x</button>
      </div>
  
      {% endfor %}
  
      {% endif %}
  {% block content %}

  {% endblock %}
  
      

        
    </body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">

templates/navbar.html
 {% load static %}
<header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'logo.svg' %}" alt="icon" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'profile' %}">Profiles</a></li>
          <li class="header__menuItem"><a href="projects.html">Appointments</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          
      
        <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
        
        <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Logout</a></li>
      
        {% else %}
        
        <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
        {% endif %}
 
        </ul>
      </nav>
    </div>
  </header>

templates/project_form.html
{% extends 'index.html' %}
{% block content %}
<h1>
    Appoint Ments
</h1>
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 {{form.as_p}}
 <input type = "submit">

</form>

{% endblock %}

templates/projects.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Doctors </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          {% for data in data %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'doctor_profile' data.id %}" class="project">
                <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{ data.name }}</hh3>
                  <p><a class="project__author" href="{% url 'doctor_profile' data.id %}">{{data.specialty}}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;"></span> {{ data.get_certification_display }}
                  </p>
                 
                  <div class="project__tags">
                    {% for item in data.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{item.name}}</small>
                    </span>
                    {% endfor %}
                  </div>
                  

                </div>
              </a>
            </div>
          </div>
          {% endfor %}


          

        </div>
      </div>
    </section>

  
  </main>
</body>

</html>

templates/reset.html
{% extends 'index.html' %}

{% block content %}

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'] {
        min-width: 24rem;
        width: 100%;
        padding: 1.2rem 1.5rem;
        border-radius: 0.5rem;
        border: 2px solid var(--color-light);
        transition: all 0.3s ease-in-out;
        background-color: var(--color-bg);
    }

    input[type='text']:focus,
    input[type='email']:focus,
    input[type='password']:focus,
    input[type='text']:active,
    input[type='email']:active,
    input[type='password']:active {
        outline: none;
        border: 2px solid var(--color-main);
    }
</style>


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Enter new password</h3>

            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

templates/reset_password.html
{% extends 'index.html' %}

{% block content %}

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'] {
        min-width: 24rem;
        width: 100%;
        padding: 1.2rem 1.5rem;
        border-radius: 0.5rem;
        border: 2px solid var(--color-light);
        transition: all 0.3s ease-in-out;
        background-color: var(--color-bg);
    }

    input[type='text']:focus,
    input[type='email']:focus,
    input[type='password']:focus,
    input[type='text']:active,
    input[type='email']:active,
    input[type='password']:active {
        outline: none;
        border: 2px solid var(--color-main);
    }
</style>


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset</h3>

            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new
                one.</p>

            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

templates/reset_password_sent.html
{% extends 'index.html' %}

{% block content %}


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset sent</h3>

            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>
            <br>
            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
                your spam folder.</p>
        </div>
    </div>
</main>

{% endblock content %}

templates/single-project.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="uikit/styles/uikit.css" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="styles/app.css" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
          {% for tags in data.tags %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ tags }}</small>
            </span>
          {% endfor %}
          </div>
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="images/project-c.png" alt="portfolio thumbnail" />
          <a href="profile.html" class="singleProject__developer">Md. Shahriar Parvez</a>
          <h2 class="singleProject__title">Portfolio Landing Page for a Coding Mentor</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima harum maxime debitis amet voluptates esse
            a perferendis tempora, natus pariatur obcaecati odit quisquam fugit deserunt.

            <br />
            <br />
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic voluptates earum possimus a perferendis culpa
            omnis, libero quae soluta, obcaecati amet. Quam earum ad qui reprehenderit eligendi porro ab possimus
            fugit voluptatem rerum eius sapiente, nemo mollitia aperiam suscipit culpa corrupti officiis dicta soluta
            ut similique! Iste soluta quae tempora alias assumenda? Nam nesciunt nihil enim tempore cum quo
            architecto?
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              36% Postitive Feedback (18 Votes)
            </h5>

            <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                  <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                  <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
</body>

</html>